name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup CMake
        runs: |
          mkdir build
          cd build
          cmake ..
          make

      # - name: execute
      #   run: ./build/main